### PR TITLE
Changed the candlestick format from LHOC to OHLC

### PR DESCRIPTION
**Pull request by WalrusGumboot**
I know this is a tiny, one-line change barely worth creating a PR for, but since the standard is OHLC I feel this greatly improves workability.

### CODE REVIEW

**Comment by sgeisler** [comment]
I think you need to adjust the tests too.

**Comment by WalrusGumboot** [comment]
How so? The only change is the order in the Candle constructor, none of the underlying functionality is altered.

**Comment by sgeisler** [comment]
There are [tests if certain candles are rendered correctly](https://github.com/sgeisler/termgraph/blob/master/test_graph.py#L35). They now have a wrong argument order.

EDIT: and don't ask me why the class is called `BloomfilterTest` :laughing: I must have copied it from another project and forgot to change it xD

**Comment by WalrusGumboot** [comment]
Should be fixed now.

**Pull request merged**
